In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv('test.csv', sep=';')
data.head(20)

,ID,Sex,Age,State,Account length,Phone number,Plans,Number vmail messages,Total day minutes,Total day calls,...,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Total charge,Customer service calls
0,10007,Male,32.0,TX,71,415 550 95 54,Voice mail,39,183.2,103.0,...,111.0,17.80,172.4,109.0,7.76,11.9,6.0,3.21,59.91,1
1,10134,Male,31.0,CT,147,415 933 19 41,None,0,124.4,74.0,...,78.0,27.28,157.2,126.0,7.07,10.4,4.0,2.81,58.31,2
2,10464,Female,NaN,UT,36,415 528 80 70,Voice mail,16,149.4,111.0,...,113.0,11.20,132.7,87.0,5.97,6.7,2.0,1.81,44.38,0
3,10490,Male,36.0,MO,167,415 720 71 11,International,0,244.8,91.0,...,105.0,5.17,176.7,110.0,7.95,10.7,3.0,2.89,57.63,2
4,10556,Female,41.0,OR,48,415 846 34 64,None,0,190.4,92.0,...,85.0,26.99,133.4,113.0,6.00,8.3,4.0,2.24,67.6,2
5,10612,Female,NaN,WV,70,415 722 49 56,None,0,214.8,87.0,...,114.0,11.14,216.9,104.0,9.76,9.4,3.0,2.54,59.96,3
6,10655,Male,33.0,SD,125,510 839 77 96,Voice mail,34,268.4,112.0,...,108.0,18.89,117.6,102.0,5.29,10.3,3.0,2.78,72.59,0
7,11070,Male,30.0,KS,128,510 318 65 40,None,0,268.1,95.0,...,126.0,10.24,220.8,121.0,9.94,14.4,6.0,3.89,69.65,2
8,11084,Male,49.0,SD,105,415 828 30 81,None,0,251.6,88.0,...,103.0,14.88,184.4,112.0,8.30,5.4,5.0,1.46,67.41,1
9,11141,Male,32.0,ME,80,408 937 17 50,Voice mail,31,166.4,92.0,...,74.0,20.26,150.7,84.0,6.78,10.7,4.0,2.89,58.22,4
10,11181,Female,NaN,MA,67,415 826 31 97,Voice mail,34,161.7,114.0,...,115.0,17.65,205.7,114.0,9.26,9.2,4.0,2.48,56.88,0
11,11264,Female,NaN,SC,111,510 165 72 81,None,0,78.3,119.0,...,94.0,16.85,248.5,94.0,11.18,12.1,4.0,3.27,44.61,1
12,11405,Female,34.0,MA,122,408 942 17 23,Voice mail,29,195.4,83.0,...,93.0,22.80,168.0,95.0,7.56,8.4,6.0,2.27,65.85,3
13,11537,Male,40.0,WY,124,415 665 66 79,None,0,178.3,102.0,...,120.0,19.98,239.7,119.0,10.79,10.9,1.0,2.94,64.02,3
14,11571,Female,NaN,WY,106,415 189 98 85,"International, Voice mail",26,270.3,111.0,...,90.0,18.29,254.0,133.0,11.43,14.4,7.0,3.89,79.56,1
15,11827,Female,40.0,IN,68,415 530 87 27,None,0,222.1,107.0,...,102.0,16.95,162.4,107.0,7.31,9.4,3.0,2.54,64.56,2
16,12028,Male,22.0,MN,115,510 429 37 13,International,0,"122,0",110.0,...,100.0,18.72,179.7,124.0,8.09,10.8,2.0,2.92,50.47,2
17,12104,Male,40.0,MO,131,408 123 69 78,None,0,109.5,95.0,...,48.0,28.23,258.6,108.0,11.64,6.6,7.0,1.78,60.27,1
18,12176,Male,38.0,MA,128,415 968 65 21,NaN,0,195.6,99.0,...,120.0,22.76,164.9,76.0,7.42,16.0,2.0,4.32,67.75,0
19,12253,Male,33.0,KY,107,415 216 56 54,None,0,157.1,79.0,...,124.0,13.82,150.0,138.0,6.75,12.1,6.0,3.27,50.55,1

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 834 entries, 0 to 833
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      834 non-null    int64
 1   Sex                     834 non-null    object
 2   Age                     576 non-null    float64
 3   State                   834 non-null    object
 4   Account length          834 non-null    int64
 5   Phone number            834 non-null    object
 6   Plans                   805 non-null    object
 7   Number vmail messages   834 non-null    int64
 8   Total day minutes       834 non-null    object
 9   Total day calls         834 non-null    object
 10  Total day charge        834 non-null    float64
 11  Total eve minutes       834 non-null    float64
 12  Total eve calls         834 non-null    float64
 13  Total eve charge        834 non-null    float64
 14  Total night minutes     834 non-null    object
 15  Total night calls       834 non-null    float64
 16  Total night charge      834 non-null    float64
 17  Total intl minutes      834 non-null    object
 18  Total intl calls        834 non-null    float64
 19  Total intl charge       834 non-null    float64
 20  Total charge            834 non-null    object
 21  Customer service calls  834 non-null    object
dtypes: float64(9), int64(3), object(10)
memory usage: 143.5+ KB

In [4]:
def str_to_float(obj):
    global NUM_ERR

    try:
        return float(obj)
    except ValueError:
        NUM_ERR += 1

        try:
            return float(obj.replace(',', '.').replace('o', '0').replace('l', '1'))
        except ValueError:
            return float(obj.replace(' hundred', '')) * 100


def str_to_int(obj):
    global NUM_ERR

    try:
        return int(obj)
    except ValueError:
        NUM_ERR += 1

        return int(obj.replace('o', '0'))

In [5]:
NUM_ERR = 0

In [6]:
for col in ['Total day minutes', 'Total day calls', 'Total night minutes', 'Total intl minutes', 'Total charge']:
    data[col] = data[col].apply(str_to_float)
    print(NUM_ERR, 'errors for "{}"'.format(col))
    NUM_ERR = 0

13 errors for "Total day minutes"
1 errors for "Total day calls"
1 errors for "Total night minutes"
6 errors for "Total intl minutes"
4 errors for "Total charge"

In [7]:
data['Customer service calls'] = data['Customer service calls'].apply(
    str_to_int)
print(NUM_ERR, 'errors for "{}"'.format('Customer service calls'))
NUM_ERR = 0

2 errors for "Customer service calls"

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 834 entries, 0 to 833
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      834 non-null    int64
 1   Sex                     834 non-null    object
 2   Age                     576 non-null    float64
 3   State                   834 non-null    object
 4   Account length          834 non-null    int64
 5   Phone number            834 non-null    object
 6   Plans                   805 non-null    object
 7   Number vmail messages   834 non-null    int64
 8   Total day minutes       834 non-null    float64
 9   Total day calls         834 non-null    float64
 10  Total day charge        834 non-null    float64
 11  Total eve minutes       834 non-null    float64
 12  Total eve calls         834 non-null    float64
 13  Total eve charge        834 non-null    float64
 14  Total night minutes     834 non-null    float64
 15  Total night calls       834 non-null    float64
 16  Total night charge      834 non-null    float64
 17  Total intl minutes      834 non-null    float64
 18  Total intl calls        834 non-null    float64
 19  Total intl charge       834 non-null    float64
 20  Total charge            834 non-null    float64
 21  Customer service calls  834 non-null    int64
dtypes: float64(14), int64(4), object(4)
memory usage: 143.5+ KB

In [9]:
from sklearn.impute import SimpleImputer
import numpy as np

imp_mode = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
data['Plans'] = imp_mode.fit_transform(np.array(data['Plans']).reshape(-1, 1))

imp_mode = SimpleImputer(missing_values=np.nan, strategy='mean')
data['Age'] = imp_mode.fit_transform(np.array(data['Age']).reshape(-1, 1))

In [10]:
data.isnull().sum()

ID                        0
Sex                       0
Age                       0
State                     0
Account length            0
Phone number              0
Plans                     0
Number vmail messages     0
Total day minutes         0
Total day calls           0
Total day charge          0
Total eve minutes         0
Total eve calls           0
Total eve charge          0
Total night minutes       0
Total night calls         0
Total night charge        0
Total intl minutes        0
Total intl calls          0
Total intl charge         0
Total charge              0
Customer service calls    0
dtype: int64

In [11]:
data['Area code'] = data['Phone number'].apply(lambda obj: obj[:3])

In [12]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
data['Sex'] = le.fit_transform(data['Sex'])

Из лб_1 для сглаженного target-кодирования:

In [13]:
pattern_state = {'AK': 0.027777777777777776,
                 'HI': 0.05405405405405406,
                 'AZ': 0.05660377358490566,
                 'LA': 0.058823529411764705,
                 'VA': 0.07272727272727272,
                 'DC': 0.07317073170731707,
                 'AL': 0.07936507936507936,
                 'IN': 0.08,
                 'IL': 0.08333333333333333,
                 'IA': 0.08571428571428572,
                 'NM': 0.08888888888888889,
                 'WI': 0.09523809523809523,
                 'WV': 0.09876543209876543,
                 'NE': 0.1,
                 'ND': 0.10638297872340426,
                 'WY': 0.10714285714285714,
                 'KY': 0.10869565217391304,
                 'RI': 0.11538461538461539,
                 'TN': 0.11764705882352941,
                 'MO': 0.12,
                 'NC': 0.12244897959183673,
                 'ID': 0.12962962962962962,
                 'OR': 0.13559322033898305,
                 'GA': 0.13636363636363635,
                 'FL': 0.13725490196078433,
                 'OH': 0.14516129032258066,
                 'MN': 0.14925373134328357,
                 'CO': 0.1509433962264151,
                 'UT': 0.1568627450980392,
                 'ME': 0.1702127659574468,
                 'AR': 0.17391304347826086,
                 'DE': 0.17777777777777778,
                 'SD': 0.1794871794871795,
                 'MA': 0.18181818181818182,
                 'KS': 0.18518518518518517,
                 'NH': 0.1891891891891892,
                 'MS': 0.20408163265306123,
                 'NY': 0.20967741935483872,
                 'PA': 0.21212121212121213,
                 'NV': 0.2222222222222222,
                 'WA': 0.22916666666666666,
                 'CA': 0.23076923076923078,
                 'MI': 0.23529411764705882,
                 'MT': 0.23636363636363636,
                 'MD': 0.25,
                 'NJ': 0.2549019607843137,
                 'SC': 0.2558139534883721}

In [14]:
pattern_plans = {'Voice mail': 0.061488673139158574,
                 'None': 0.13849908480780965,
                 'International, Voice mail': 0.38666666666666666,
                 'International': 0.40718562874251496}

In [15]:
pattern_area_code = {'415': 0.136327185244587,
                     '510': 0.15, '408': 0.15664556962025317}

In [16]:
data['State'] = data['State'].map(pattern_state)
data['Plans'] = data['Plans'].map(pattern_plans)
data['Area code'] = data['Area code'].map(pattern_area_code)

In [17]:
data.isnull().sum()

ID                         0
Sex                        0
Age                        0
State                     74
Account length             0
Phone number               0
Plans                      0
Number vmail messages      0
Total day minutes          0
Total day calls            0
Total day charge           0
Total eve minutes          0
Total eve calls            0
Total eve charge           0
Total night minutes        0
Total night calls          0
Total night charge         0
Total intl minutes         0
Total intl calls           0
Total intl charge          0
Total charge               0
Customer service calls     0
Area code                  0
dtype: int64

In [18]:
data['State'] = imp_mode.fit_transform(np.array(data['State']).reshape(-1, 1))

In [19]:
data.drop(columns=['Total day charge', 'Total eve charge',
                   'Total night charge', 'Total intl charge',
                   'Total day minutes', 'Phone number'], inplace=True)

In [22]:
import pickle

loaded_model = pickle.load(open('kaggle_model.sav', 'rb'))
y_pred = loaded_model.predict(data.drop(columns=['ID']))

results_df = pd.DataFrame(data={'ID': data['ID'], 'Churn': y_pred})
results_df.to_csv('Submission.csv', index=False)